Repository timble/kodekit, pull requests merged in 2019-07, with the labels that each got.

#197 Merge feature/196-union
  code/database/query/union.php
Labels: feature

#201 JSON resource structure
  code/view/json.php
Labels: bug, refactor

#205 Load component base translations in localizable
  code/dispatcher/behavior/localizable.php
Labels: refactor
